INSERT INTO `departamento` VALUES (5, 'ANTIOQUIA');
INSERT INTO `departamento` VALUES (8, 'ATLÁNTICO');
INSERT INTO `departamento` VALUES (11, 'BOGOTÁ, D.C.');
INSERT INTO `departamento` VALUES (13, 'BOLÍVAR');
INSERT INTO `departamento` VALUES (15, 'BOYACÁ');
INSERT INTO `departamento` VALUES (17, 'CALDAS');
INSERT INTO `departamento` VALUES (18, 'CAQUETÁ');
INSERT INTO `departamento` VALUES (19, 'CAUCA');
INSERT INTO `departamento` VALUES (20, 'CESAR');
INSERT INTO `departamento` VALUES (23, 'CÓRDOBA');
INSERT INTO `departamento` VALUES (25, 'CUNDINAMARCA');
INSERT INTO `departamento` VALUES (27, 'CHOCÓ');
INSERT INTO `departamento` VALUES (41, 'HUILA');
INSERT INTO `departamento` VALUES (44, 'LA GUAJIRA');
INSERT INTO `departamento` VALUES (47, 'MAGDALENA');
INSERT INTO `departamento` VALUES (50, 'META');
INSERT INTO `departamento` VALUES (52, 'NARIÑO');
INSERT INTO `departamento` VALUES (54, 'NORTE DE SANTANDER');
INSERT INTO `departamento` VALUES (63, 'QUINDIO');
INSERT INTO `departamento` VALUES (66, 'RISARALDA');
INSERT INTO `departamento` VALUES (68, 'SANTANDER');
INSERT INTO `departamento` VALUES (70, 'SUCRE');
INSERT INTO `departamento` VALUES (73, 'TOLIMA');
INSERT INTO `departamento` VALUES (76, 'VALLE DEL CAUCA');
INSERT INTO `departamento` VALUES (81, 'ARAUCA');
INSERT INTO `departamento` VALUES (85, 'CASANARE');
INSERT INTO `departamento` VALUES (86, 'PUTUMAYO');
INSERT INTO `departamento` VALUES (88, 'SAN ANDRÉS');
INSERT INTO `departamento` VALUES (91, 'AMAZONAS');
INSERT INTO `departamento` VALUES (94, 'GUAINÍA');
INSERT INTO `departamento` VALUES (95, 'GUAVIARE');
INSERT INTO `departamento` VALUES (97, 'VAUPÉS');
INSERT INTO `departamento` VALUES (99, 'VICHADA');
INSERT INTO `departamento` VALUES (9999, '');